# Data-X Spring 2019: Homework 06 

## Name : Zhang Jiaheng
## SID : 3034453700
## Course (IEOR 135/290) : IEOR 135

### Machine Learning



In this homework, you will do some exercises with prediction. We will cover these algorithms in class, but this is for you to have some hands on with these in scikit-learn. You can refer - https://github.com/ikhlaqsidhu/data-x/blob/master/05a-tools-predicition-titanic/titanic.ipynb

Display all your outputs.


In [1]:
import numpy as np
import pandas as pd

In [2]:
 # machine learning libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier



__ 1. Read __`diabetesdata.csv`__ file into a pandas dataframe. 
About the data: __

1. __TimesPregnant__: Number of times pregnant 
2. __glucoseLevel__: Plasma glucose concentration a 2 hours in an oral glucose tolerance test 
3. __BP__: Diastolic blood pressure (mm Hg)  
5. __insulin__: 2-Hour serum insulin (mu U/ml) 
6. __BMI__: Body mass index (weight in kg/(height in m)^2) 
7. __pedigree__: Diabetes pedigree function 
8. __Age__: Age (years) 
9. __IsDiabetic__: 0 if not diabetic or 1 if diabetic) 








In [3]:
#Read data & print the head
df = pd.read_csv('diabetesdata.csv')
df.head()


TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  IsDiabetic
0              6         148.0  72        0  33.6     0.627  50.0           1
1              1           NaN  66        0  26.6     0.351  31.0           0
2              8         183.0  64        0  23.3     0.672   NaN           1
3              1           NaN  66       94  28.1     0.167  21.0           0
4              0         137.0  40      168  43.1     2.288  33.0           1

**2. Calculate the percentage of Null values in each column and display it. **

In [5]:
for column in df:
    ratio = df[column].isna().sum()/len(df[column])
    print("{}: {}%".format(column, ratio*100))

TimesPregnant: 0.0%
glucoseLevel: 4.427083333333334%
BP: 0.0%
insulin: 0.0%
BMI: 0.0%
Pedigree: 0.0%
Age: 4.296875%
IsDiabetic: 0.0%


**3. Split __`data`__  into  __`train_df`__ and __`test_df`__  with 15% as test.**


In [6]:
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(df, test_size=0.15)
print(train_df)
print(test_df)

     TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
69               4         146.0  85      100  28.9     0.189  27.0   
364              4         147.0  74      293  34.9     0.385  30.0   
558             11         103.0  68        0  46.2     0.126  42.0   
741              3         102.0  44       94  30.8     0.400  26.0   
170              6         102.0  82        0  30.8     0.180  36.0   
699              4         118.0  70        0  44.5     0.904  26.0   
123              5         132.0  80        0  26.8     0.186  69.0   
451              2         134.0  70        0  28.9     0.542  23.0   
159             17         163.0  72      114  40.9     0.817  47.0   
75               1           0.0  48        0  24.7     0.140   NaN   
223              7         142.0  60      190  28.8     0.687  61.0   
336              0         117.0   0        0  33.8     0.932  44.0   
609              1         111.0  62      182  24.0     0.138  23.0   
247   

**4. Display the means of the features in train and test sets. Replace the null values in  __`train_df`__ and __`test_df`__  with the mean of EACH feature column separately for train and test. Display head of the dataframes.**

In [7]:
for column in train_df:
    print("%s, %f"%(column, train_df[column].mean()))
print('\ntrain_df complete') 
print('starting mean for test_df\n')
for column2 in test_df:
    print("%s, %f"%(column2, test_df[column2].mean()))
    
###We can see which columns have null values in the above qn(2)
train_df.fillna(value={'glucoseLevel':120.849359}, inplace=True)
train_df.fillna(value={'Age':33.410543}, inplace=True)

test_df.fillna(value={'glucoseLevel':121.963636}, inplace=True)
test_df.fillna(value={'Age':33.027523}, inplace=True)

###Double Check
print('\nDouble Check\n')
for column in train_df:
    ratio = train_df[column].isna().sum()/len(train_df[column])
    print("{}: {}%".format(column, ratio*100))

print('\ntrain_df complete') 
print('starting mean for test_df\n')

for column in test_df:
    ratio = test_df[column].isna().sum()/len(test_df[column])
    print("{}: {}%".format(column, ratio*100))


TimesPregnant, 3.838957
glucoseLevel, 121.329053
BP, 69.012270
insulin, 80.354294
BMI, 32.098620
Pedigree, 0.475106
Age, 33.435897
IsDiabetic, 0.365031

train_df complete
starting mean for test_df

TimesPregnant, 3.879310
glucoseLevel, 119.261261
BP, 69.629310
insulin, 76.681034
BMI, 31.396552
Pedigree, 0.453724
Age, 32.891892
IsDiabetic, 0.258621

Double Check

TimesPregnant: 0.0%
glucoseLevel: 0.0%
BP: 0.0%
insulin: 0.0%
BMI: 0.0%
Pedigree: 0.0%
Age: 0.0%
IsDiabetic: 0.0%

train_df complete
starting mean for test_df

TimesPregnant: 0.0%
glucoseLevel: 0.0%
BP: 0.0%
insulin: 0.0%
BMI: 0.0%
Pedigree: 0.0%
Age: 0.0%
IsDiabetic: 0.0%


/Users/jiahengzhang/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5434: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


**5. Split __`train_df`__ & __`test_df`__   into  __`X_train`__, __`Y_train`__  and __`X_test`__, __`Y_test`__. __`Y_train`__  and __`Y_test`__ should only have the column we are trying to predict,  __`IsDiabetic`__.**

In [8]:
X_train = train_df.iloc[:,:7]
Y_train = train_df['IsDiabetic']
X_test = test_df.iloc[:,:7]
Y_test = test_df['IsDiabetic']

print('\nX_train\n')
print(X_train)
print('\nY_train\n')
print(Y_train)
print('\nX_test\n')
print(X_test)
print('\nY_test\n')
print(Y_test)

print(X_train.shape, Y_train.shape, X_test.shape, Y_test.shape)



X_train

     TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree        Age
69               4    146.000000  85      100  28.9     0.189  27.000000
364              4    147.000000  74      293  34.9     0.385  30.000000
558             11    103.000000  68        0  46.2     0.126  42.000000
741              3    102.000000  44       94  30.8     0.400  26.000000
170              6    102.000000  82        0  30.8     0.180  36.000000
699              4    118.000000  70        0  44.5     0.904  26.000000
123              5    132.000000  80        0  26.8     0.186  69.000000
451              2    134.000000  70        0  28.9     0.542  23.000000
159             17    163.000000  72      114  40.9     0.817  47.000000
75               1      0.000000  48        0  24.7     0.140  33.410543
223              7    142.000000  60      190  28.8     0.687  61.000000
336              0    117.000000   0        0  33.8     0.932  44.000000
609              1    111.000000  62     

**6. Use this dataset to train perceptron, logistic regression and random forest models using 15% test split. Report training and test accuracies. Try different hyperparameter values for these models and see if you can improve your accuracies.**

In [9]:
# 6a. Logistic Regression
logreg = LogisticRegression()
logreg.fit(X_train, Y_train)
Y_pred = logreg.predict(X_test)
acc_logreg = sum(Y_pred == Y_test)/len(Y_test)*100

print('Logistic Regression labeling accuracy:', str(round(acc_logreg,2)),'%')

Logistic Regression labeling accuracy: 81.9 %


/Users/jiahengzhang/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [13]:
# 6b. Perceptron
perceptron = Perceptron(penalty='elasticnet',alpha=0.01,max_iter=100,early_stopping=True,validation_fraction=0.01)
perceptron.fit(X_train, Y_train)
acc_perceptron = perceptron.score(X_test, Y_test)

print('Perceptron labeling accuracy:', str(round(acc_perceptron*100,2)),'%')


Perceptron labeling accuracy: 68.1 %


/Users/jiahengzhang/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


In [16]:
# 6c. Random Forest
random_forest = RandomForestClassifier(n_estimators=700)
random_forest.fit(X_train, Y_train)
acc_rf = random_forest.score(X_test, Y_test)

print('Random Forest labelling accuracy:', str(round(acc_rf*100,2)),'%')


Random Forest labelling accuracy: 81.9 %


**7. For your logistic regression model - **

**a . Compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your train set and display it. Also display the predicted class for those samples from your logistic regression model trained before. **


In [26]:
ten_samples_trainX = X_train[:10]
result_trainY = logreg.predict(ten_samples_trainX)
ten_samples_trainY = Y_train[:10]
log_likelihood_elements = logreg.predict_proba(ten_samples_trainX)
print('\nLog Probabilities\n')
print(log_likelihood_elements)
print('\nPredicted Values\n')
print(result_trainY)


Log Probabilities

[[0.64142553 0.35857447]
 [0.52323052 0.47676948]
 [0.4628212  0.5371788 ]
 [0.75387189 0.24612811]
 [0.79412337 0.20587663]
 [0.44732244 0.55267756]
 [0.61172379 0.38827621]
 [0.64484288 0.35515712]
 [0.06503828 0.93496172]
 [0.99072795 0.00927205]]

Predicted Values

[0 0 1 0 0 1 0 0 1 0]


**b . Now compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your test set and display it. Also display the predicted class for those samples from your logistic regression model trained before.
 (using the model trained on the training set)**


In [27]:
ten_samples_testX = X_test[:10]
result_testY = logreg.predict(ten_samples_testX)
ten_samples_testY = Y_test[:10]
log_likelihood_elements_test = logreg.predict_proba(ten_samples_testX)
print('\nLog Probabilities\n')
print(log_likelihood_elements_test)
print('\nPredicted Values\n')
print(result_testY)


Log Probabilities

[[0.83327598 0.16672402]
 [0.804337   0.195663  ]
 [0.59284604 0.40715396]
 [0.36107874 0.63892126]
 [0.1715084  0.8284916 ]
 [0.78030903 0.21969097]
 [0.88926905 0.11073095]
 [0.27708538 0.72291462]
 [0.92204697 0.07795303]
 [0.55430689 0.44569311]]

Predicted Values

[0 0 0 1 1 0 0 1 0 0]


**c . What can you interpret from the log probabilities and the predicted classes?**



As long as the log probability of a certain label is above 50%, the model would choose to output the label as the predicted label

There is still a significant amount of uncertainty in the prediction, as we can see that some of the probabilities for each label is similar (50+% to 40+%

**8. Is mean imputation is the best type of imputation (as we did in 4.) to use? Why or why not? What are some other ways to impute the data?**

Your answer here

In [29]:
Mean imputation has an advantage of keeping the same mean and 
same sample size, but this could be inaccurate as this could introduce
inaccurate data if the value is actually significantly larger/lower 
than the mean.
Some other methods include substitution: Impute the value from a
new individual who was not selected to be in the sample.
Hot Deck Implementation: A randomly chosen value from an individual 
in the sample who has similar values on other variables.
Cold deck imputation: A systematically chosen value from an 
individual who has similar values on other variables.
Regression imputation: The predicted value obtained by 
regressing the missing variable on other variables.
Stochastic regression imputation: The predicted value 
from a regression plus a random residual value.
Interpolation and extrapolation: An estimated value from other 
observations from the same individual. It usually only works in 
longitudinal data.



SyntaxError: invalid syntax (<ipython-input-29-bdfba6ebf238>, line 1)

## Extra Credit (2 pts) - MANDATORY for students enrolled in IEOR 290


**9.  Implement the K-Nearest Neighbours (https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm) algorithm for k=1 from scratch in python (do not use KNN from existing libraries). KNN uses Euclidean distance to find nearest neighbors. Split your dataset into test and train as before. Also fill in the null values with mean of features as done earlier. Use this algorithm to predict values for 'IsDiabetic' for your test set. Display your accuracy. **